name: Continous Intergration
on: [push]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing Build
        run: docker build --target test --tag table-tennis-table:testing .
           - docker run table-tennis-table:testing